AAAAAAAAAAAA
BBBBBBBBBBBB
cccccccccc
dddddddd
eeeeeeeeeeeee
ffffffffffffff
gggggggggggggggggg
hhhhhhhhhhhhhhhh
iiiiiiiiiiiiii
jjjjjjjjjjjjjjjj
kkkkkkkkkkkkkkkkkkkk
llllllllllll
mmmmmmmmmmmmmmmmm
nnnnnnnnnnnnnnnnnnn
Copy taken from Mohan
 krian perfect in aws 